sensor:
  - platform: openweathermap
    api_key: !secret openweatherkey
    monitored_conditions:
      - weather
      - temperature
      - wind_speed
      - humidity
      - pressure
      - clouds
      - rain
      - snow
