homeassistant:
  name: !secret name
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 7
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  customize: !include customize.yaml
  packages:
    pack_1: !include packages/arduino.yaml
    pack_2: !include packages/octoprint.yaml


frontend:

http:
  api_password: !secret http_apipassword
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret sslkey
  base_url: !secret baseurl

updater:
conversation:
history:
logbook:

sun:

mqtt:
  broker: !secret mqttbroker
  port: 1883
  client_id: home-assistant-1
  username: !secret mqttuser
  password: !secret mqttpass

alarm_control_panel:
  - platform: manual
    name: Avondale Alarm
    code: !secret alarmcode

google:
  client_id: !secret googleid
  client_secret: !secret googlesecret

scene: !include scene.yaml

script: !include_dir_merge_named script

alexa: !include alexa.yaml

shell_command:
  hibernatelinux: "ssh ubuntu sudo pm-hibernate"
  startmirror: "pm2 start /home/pi/mm.sh"

tts:
  - platform: google
  - platform: voicerss
    api_key: !secret voicerss
    language: en-gb
  - platform: picotts
    language: en-GB
  # - platform: yandextts
  #   api_key: !secret yandextts
  #   language: 'en-EN'

digital_ocean:
  access_token: !secret digocean

input_select:
  tempfor6:
    name: Set temperature for 6am
    options:
      - 5
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
    initial: 19
  tempfornormal:
    name: Set the normal temperature
    options:
      - 5
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
    initial: 18
  preheatdelay:
    name: morning preheat length
    options:
      - 00:01
      - 00:30
      - 01:00
      - 01:30
      - 02:00
      - 02:30
    initial: 01:00
  boostdelay:
    name: Boost heating length
    options:
      - 00:01
      - 00:30
      - 01:00
      - 01:30
      - 02:00
      - 02:30
    initial: 01:00
  away_from_home_temp:
    name: temperature for when away from home
    options:
      - 5
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
    initial: 17


proximity:
  home:
    ignored_zones:
      - Parents
      - Cornwall
    devices:
      - device_tracker.pi_nexus
    tolerance: 50
    unit_of_measurement: mi

switch: !include switch.yaml

input_slider:
  slider1:
    name: temperature
    initial: 22
    min: 10
    max: 30
    step: 1

light:
  - platform: hue
    host: !secret huebridgeip
    allow_unreachable: true
  - platform: mqtt
    name: heating
    command_topic: 'avondale/temp/poo/switch'
    state_topic: 'avondale/temp/poo/status'
    brightness_command_topic: 'avondale/temp/set'
    brightness_state_topic: 'avondale/temp/set'
    optimistic: false
    brightness_scale: 102
  - platform: mqtt
    name: 'Bed light'
    state_topic: 'bed/rgb1/light/status'
    command_topic: 'bed/rgb1/light/switch'
    brightness_state_topic: 'bed/rgb1/brightness/status'
    brightness_command_topic: 'bed/rgb1/brightness/set'
    rgb_state_topic: 'bed/rgb1/rgb/status'
    rgb_command_topic: 'bed/rgb1/rgb/set'
    brightness_scale: 100
    optimistic: false

binary_sensor:
  - platform: mqtt
    state_topic: 'alarm/hall/status'
    name: 'Hall Motion'
    sensor_class: motion

notify:
  - name: kodi
    platform: kodi
    host: !secret kodihost
    username: !secret kodiuser
    password: !secret kodipass
    port: 80
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet

sensor: !include sensor.yaml

media_player:
  - platform: kodi
    host: !secret kodihost
    port: 80
    name: Kodi
    username: !secret kodiuser
    password: !secret kodipass
    turn_off_action: reboot
  - platform: cast
  - platform: kodi
    host: !secret kodibedhost
    port: 80
    name: bedroom
    username: !secret kodibeduser
    password: !secret kodibedpass
    turn_off_action: reboot

emulated_hue:
  host_ip: !secret hueip
  listen_port: 8300
  exposed_domains:
    - media_player
    - switch
    - light

ifttt:
  key: !secret ifkey

device_tracker:
  - platform: unifi
    host: !secret unifihost
    port: 8443
    username: !secret unifiuser
    password: !secret unifipass
    site_id: !secret unifiid
    track_new_devices: False
    consider_home: 420
  - platform: owntracks
    max_gps_accuracy: 300
    waypoints: True
  - platform: nmap_tracker
    hosts: 10.10.10.1/24


climate:
  - platform: generic_thermostat
    name: Home
    heater: switch.boiler
    target_sensor: sensor.lounge_temperature
    min_temp: 7
    max_temp: 32
    target_temp: 19

group: !include group.yaml

automation: !include_dir_merge_list automation

zone:
  name: Uni
  latitude: !secret 1latitude
  longitude: !secret 1longitude
  radius: 1000
  icon: mdi:school

zone 2:
  name: Hospital
  latitude: !secret 2latitude
  longitude: !secret 2longitude
  icon: mdi:hospital
  radius: 300

zone 3:
  name: Home
  latitude: !secret 3latitude
  longitude: !secret 3longitude
  radius: 200
  icon: mdi:home

zone 4:
  name: Parents
  latitude: !secret 4latitude
  longitude: !secret 4longitude
  radius: 400
  icon: mdi:home

zone 5:
  name: Cornwall
  latitude: !secret 5latitude
  longitude: !secret 5longitude
  radius: 1000
  icon: mdi:home-variant

zone 6:
  name: Andys
  latitude: !secret 6latitude
  longitude: !secret 6longitude
  radius: 200
  icon: mdi:heart

zone 7:
  name: Danny
  latitude: !secret 7latitude
  longitude: !secret 7longitude
  radius: 200
  icon: mdi:heart

zone 8:
  name: Barrow
  latitude: !secret 8latitude
  longitude: !secret 8longitude
  radius: 1000
  icon: mdi:hospital

  # notes
  # threshhold sensor to the outside temp
  # set an automation with the threshold as a condition
  # below the threshold tunr heating onn sooner and higher
