homeassistant:
  name: !secret name
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 7
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  customize: !include customize.yaml
  packages:
    pack_1: !include_dir_merge_named packages/lounge
    pack_2: !include packages/bedroom.yaml
    pack_3: !include_dir_merge_named packages/heating
    pack_15: !include packages/calendar.yaml
    pack_16: !include packages/kitchen.yaml
    pack_4: !include packages/hall.yaml
    pack_5: !include_dir_merge_named packages/garden
    pack_6: !include packages/tinterweb.yaml
    # pack_7: !include packages/weather.yaml
    # pack_8: !include_dir_merge_named packages/testing
    # pack_12: !include packages/androidtab.yaml
    #######   non tabs
    pack_9: !include packages/loungelightswitch.yaml
    pack_10: !include packages/rebootpi.yaml
    pack_11: !include packages/arduino.yaml
    pack_12: !include packages/octoprint.yaml
    pack_13: !include packages/herokukeepalive.yaml
    pack_14: !include packages/rss.yaml
config:

frontend:
  themes:
    green:
      primary-color: "#6CA518"
    Haz:
      primary-color: "#cc33ff"

http:
  api_password: !secret http_apipassword
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret sslkey
  base_url: !secret baseurl
# panel_custom:
#   - name: react
#     sidebar_title: TodoMVC
#     sidebar_icon: mdi:checkbox-marked-outline
#     config:
#       title: Wow hello!
# panel_iframe:
#   router:
#     title: 'Router'
#     url: https://10.10.10.1
#   garden:
#     title: 'Garden'
#     url: 'http://10.10.10.76'
#   printer:
#     title: 'Printer'
#     url: http://10.10.10.195
#   tv:
#     title: 'Tele'
#     url: http://10.10.10.83
#   admin:
#     title: 'Admin'
#     url: https://10.10.10.40:10000
updater:
conversation:
history:
logbook:
sun:

# switch: !include switch.yaml
sensor: !include sensor.yaml
# scene: !include scene.yaml
# script: !include_dir_merge_named script
alexa:
apiai:
intent_script: !include intent.yaml
group: !include group.yaml
automation: !include_dir_merge_list automation

mqtt:
  broker: !secret mqttbroker
  port: 1883
  client_id: sam-home
  username: !secret mqttuser
  password: !secret mqttpass

google:
  client_id: !secret googleid
  client_secret: !secret googlesecret

shell_command:
  hibernatelinux: "ssh ubuntu sudo pm-hibernate"
  startdash: ssh pi@127.0.0.1 cd hadashboard && dashing start &
  starthapush: ssh pi@127.0.0.1 cd hadashboard/hapush && ./hapush.py hapush.cfg &


tts:
  - platform: google
  - platform: voicerss
    api_key: !secret voicerss
    language: en-gb
  - platform: picotts
    language: en-GB
  - platform: yandextts
    api_key: !secret yandextts
    language: 'uk-UK'

proximity:
  home:
    ignored_zones:
      - Parents
      - Cornwall
    devices:
      - device_tracker.pi_mate9
    tolerance: 50
    unit_of_measurement: mi

light:
  - platform: hue
    host: !secret huebridgeip
    allow_unreachable: true
    allow_in_emulated_hue: false
    allow_hue_groups: false

notify:
  - name: kodi
    platform: kodi
    host: !secret kodihost
    username: !secret kodiuser
    password: !secret kodipass
    port: 80
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet
  - name: printer
    platform: command_line
    command: ""

emulated_hue:
  host_ip: !secret hueip
  listen_port: 8300
  exposed_domains:
    # - media_player
    - switch
    - light

ifttt:
  key: !secret ifkey

device_tracker:
 - platform: unifi
   host: !secret unifihost
   port: 8443
   username: !secret unifiuser
   password: !secret unifipass
   site_id: !secret unifiid
   track_new_devices: False
   consider_home: 600
   verify_ssl: false
 - platform: owntracks
   max_gps_accuracy: 300
   waypoints: True

input_select:
  liz_status_dropdown:
    name: Lizzie
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
    initial: Home
  haz_status_dropdown:
    name: Hazbag
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
    initial: Home
  kristen_status_dropdown:
    name: Kristen
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
    initial: Home


zone:
  name: Uni
  latitude: !secret 1latitude
  longitude: !secret 1longitude
  radius: 1000
  icon: mdi:school

zone 2:
  name: Hospital
  latitude: !secret 2latitude
  longitude: !secret 2longitude
  icon: mdi:hospital
  radius: 300

zone 3:
  name: Home
  latitude: !secret 3latitude
  longitude: !secret 3longitude
  radius: 200
  icon: mdi:home

zone 4:
  name: Parents
  latitude: !secret 4latitude
  longitude: !secret 4longitude
  radius: 400
  icon: mdi:home

zone 5:
  name: Cornwall
  latitude: !secret 5latitude
  longitude: !secret 5longitude
  radius: 1000
  icon: mdi:home-variant

zone 6:
  name: Andys
  latitude: !secret 6latitude
  longitude: !secret 6longitude
  radius: 200
  icon: mdi:heart

zone 7:
  name: Dannys
  latitude: !secret 7latitude
  longitude: !secret 7longitude
  radius: 200
  icon: mdi:heart

zone 8:
  name: Barrow
  latitude: !secret 8latitude
  longitude: !secret 8longitude
  radius: 1000
  icon: mdi:hospital

zone 9:
  name: Rosies
  latitude: !secret 9latitude
  longitude: !secret 9longitude
  radius: 200
  icon: mdi:home-variant
