
################################   update   ####################################
  - alias: 'Update Available Notifications'
    trigger:
      platform: state
      entity_id: updater.updater
    action:
      service: notify.pushbullet
      data:
        message: 'Update for Home Assistant is available.'

################################################################################
#                       light switch
################################################################################

  - alias: all on
    trigger:
      platform: state
      entity_id: sensor.allonoff
      to: "ON"
    action:
      service: homeassistant.turn_on
      entity_id: script.loungeon
  - alias: all off
    trigger:
      platform: state
      entity_id: sensor.allonoff
      to: "OFF"
    action:
      service: homeassistant.turn_on
      entity_id: script.loungeoff
