automation:
##############################################################
##############################################################
#            lights based on location and sun
##############################################################
##############################################################
  - alias: Turn on light when sun sets
    hide_entity: False
    trigger:
      platform: sun
      event: sunset
      offset: "-01:00:00"
    condition:
     condition: state
     entity_id: group.all_devices
     state: home
    action:
      - service: homeassistant.turn_on
        entity_id: script.evening
      - service: notify.kodi
        data:
          message: "This was done automatically"
          title: "Turning the lights on ready for sunset in an hour"
  - alias: lights on when someone gets home
    hide_entity: False
    trigger:
      platform: state
      entity_id: group.all_devices
      to: home
    condition:
     condition: state
     entity_id: sun.sun
     state: below_horizon
    action:
      - service: homeassistant.turn_on
        entity_id: script.return_home
      - service: notify.kodi
        data:
          message: "This was done automatically"
          title: "Turning the lights as someone has arrived home"

######## off
  - alias: lights out after midnight
    hide_entity: False
    trigger:
      platform: time
      at: '00:00:01'
    action:
      service: scene.turn_on
      entity_id: scene.loungeoff

  - alias: lights out after 2am
    hide_entity: False
    trigger:
      platform: time
      at: '02:00:01'
    action:
      service: scene.turn_on
      entity_id: scene.loungeoff

  - alias: Turn everything off when people leave
    hide_entity: False
    trigger:
      platform: state
      entity_id: group.all_devices
      to: not_home
      for:
        seconds: 600
    action:
      - service: homeassistant.turn_off
        entity_id:
          - group.bedroom
      - service: scene.turn_on
        entity_id: scene.loungeoff
################# spotify music off when tv plays #################
  - alias: turn off spotify when the tv plays
    trigger:
      platform: state
      entity_id: media_player.kodi
      to: playing
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: media_player.spotify
          state: playing
        - condition: state
          entity_id: sensor.echo
          state: "Sam's Echo"
    action:
      - service: media_player.media_pause
        entity_id: media_player.spotify

####################### turn on lights from switch ############################
  - alias: light on from lightswitch
    trigger:
      platform: mqtt
      topic: avondale/7/switch
      payload: 'ON'
    action:
      - service: homeassistant.toggle
        entity_id: light.lamp
  - alias: light off from lightswitch
    trigger:
      platform: mqtt
      topic: avondale/7/switch
      payload: 'OFF'
    action:
      - service: homeassistant.toggle
        entity_id: light.lamp

################### lights off with tv
#Condition beginning 30 min before sunset (and including after sunset): https://home-assistant.io/docs/scripts/conditions/#sun-condition
# - condition: sun
#   after: sunset
  # after_offset: "-0:30:00"
#Condition ending 30 min after sunrise (and including before sunrise)
# - condition: sun
#   before: sunrise
#   before_offset: "-0:30:00"

  - alias: lights from pause
    trigger:
      platform: state
      entity_id: media_player.kodi
      to: paused
    condition:
      condition: and
      conditions:
        - condition: sun
          after: sunset
          after_offset: "-01:00:00"
    action:
      - service: scene.turn_on
        entity_id: scene.tv_pause

  - alias: lights from idle
    trigger:
      platform: state
      entity_id: media_player.kodi
      to: idle
    condition:
      condition: and
      conditions:
        - condition: sun
          after: sunset
          after_offset: "-01:00:00"
    action:
      - service: scene.turn_on
        entity_id: scene.tv_idle

  - alias: lights from Movie
    trigger:
      platform: state
      entity_id: media_player.kodi
      to: playing
    condition:
      condition: and
      conditions:
        - condition: sun
          after: sunset
          after_offset: "-01:00:00"
        - condition: state
          entity_id: sensor.koditype2
          state: movie
    action:
      - service: scene.turn_on
        entity_id: scene.movie

  - alias: lights from tv show
    trigger:
      platform: state
      entity_id: media_player.kodi
      to: playing
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sensor.koditype
          state: tvshow
        - condition: sun
          after: sunset
          after_offset: "-01:00:00"
    action:
      - service: scene.turn_on
        entity_id: scene.tv_show

  - alias: lights from PVR
    trigger:
      platform: state
      entity_id: media_player.kodi
      to: playing
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sensor.koditype2
          state: pvr
        - condition: sun
          after: sunset
          after_offset: "-01:00:00"
    action:
      - service: scene.turn_on
        entity_id: scene.pvr
