switch:
  - platform: mqtt
    name: boiler
    state_topic: 'avondale/boiler/status'
    command_topic: 'avondale/boiler/switch'
    optimistic: false
#switch.yaml line 34
sensor:
  - platform: mold_indicator
    indoor_temp_sensor: sensor.lounge_temperature
    indoor_humidity_sensor: sensor.lounge_humidity
    outdoor_temp_sensor: sensor.owm_temperature
    calibration_factor: 2.0
#line 1
  - platform: mqtt
    state_topic: "avondale/temp/set"
    name: Target temperature
    unit_of_measurement: "°C"
  - platform: mqtt
    state_topic: 'avondale/temp/both'
    name: 'Lounge temperature'
    unit_of_measurement: '°C'
    value_template: '{{ value_json.temperature }}'
  - platform: mqtt
    state_topic: 'avondale/temp/both'
    name: 'Lounge humidity'
    unit_of_measurement: '%'
    value_template: '{{ value_json.humidity }}'
# line 57
group:
  Heating:
    view: yes
    icon: mdi:radiator
    entities:
      - switch.boiler
      - climate.home
      - sensor.target_temperature
      - sensor.lounge_temperature
      - sensor.lounge_humidity
      - sensor.mold_indicator
      - group.auto_heating_settings
      - group.set_the_temperature
      - script.boost_the_heating
      - group.boost
  Thermostat quick settings:
    entities:
      - switch.boiler
      - input_slider.slider1
      - climate.home
  Auto heating settings:
    entities:
      - input_select.tempfor6
      - input_select.preheatdelay
      - input_select.tempfornormal
      - input_select.away_from_home_temp
      - automation.set_heating_to_21_if_below_3_degrees_outside_in_morning
      - automation.heating_on_at_6


climate:
  - platform: generic_thermostat
    name: Home
    heater: switch.boiler
    target_sensor: sensor.lounge_temperature
    min_temp: 7
    max_temp: 32
    target_temp: 19

light: #to allow alexa to control the temp
  - platform: mqtt
    name: heating
    command_topic: 'avondale/temp/poo/switch'
    state_topic: 'avondale/temp/poo/status'
    brightness_command_topic: 'avondale/temp/set'
    brightness_state_topic: 'avondale/temp/set'
    optimistic: false
    brightness_scale: 102

input_slider:
  slider1:
    name: temperature
    initial: 22
    min: 10
    max: 30
    step: 1
input_select:
  tempfor6:
    name: Set temperature for 6am
    options:
      - 5
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
    initial: 19
  tempfornormal:
    name: Set the normal temperature
    options:
      - 5
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
    initial: 18
  preheatdelay:
    name: morning preheat length
    options:
      - 00:01
      - 00:30
      - 01:00
      - 01:30
      - 02:00
      - 02:30
    initial: 01:00
  boostdelay:
    name: Boost heating length
    options:
      - 00:01
      - 00:30
      - 01:00
      - 01:30
      - 02:00
      - 02:30
    initial: 01:00
  away_from_home_temp:
    name: temperature for when away from home
    options:
      - 5
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
    initial: 17

alexa:
  WhatTempIntent:
    action:
      service_template: notify.kodi
      data_template:
        message: "It is currently {{ states.sensor.lounge_temperature.state }} degrees and the heating is set to {{ states.sensor.target_temperature.state }}"
        title: "Somebody asked alexa about the temperature"
    speech:
      type: plaintext
      text: >
        It is currently {{ states.sensor.lounge_temperature.state }} degrees and the heating is set to {{ states.sensor.target_temperature.state }}
