digital_ocean:
  access_token: !secret digocean

switch:
  - platform: digital_ocean
    droplets:
      - 'ubuntu-512mb-sgp1-01'

binary_sensor:
  - platform: digital_ocean
    droplets:
      - 'ubuntu-512mb-sgp1-01'
