digital_ocean:
  access_token: !secret digocean

switch:
  - platform: digital_ocean
    droplets:
      - !secret digoceandroplet1

binary_sensor:
  - platform: digital_ocean
    droplets:
      - !secret digoceandroplet1
