binary_sensor:
  - platform: mqtt
    state_topic: 'alarm/hall/status'
    name: 'Hall Motion'
    sensor_class: motion
script:
  halldim:
    alias: Hall on dim
    sequence:
      - service: homeassistant.turn_on
        data:
          entity_id: light.hall_light
          brightness: 75
  hallbright:
    alias: Hall on bright
    sequence:
      - service: homeassistant.turn_on
        data:
          entity_id: light.hall_light
          brightness: 255

alarm_control_panel:
  - platform: manual
    name: Avondale Alarm
    code: !secret alarmcode

group:
  Hallway:
    entities:
      - light.hall_light
  Hall:
    view: yes
    icon: mdi:stairs
    entities:
      - automation.hallbright
      - automation.halldim
      - automation.halloff
      - script.halldim
      - script.hallbright
      - binary_sensor.hall_motion
      - light.hall_light
      - alarm_control_panel.avondale_alarm

automation:
  - alias: hallbright
    trigger:
      platform: state
      entity_id: binary_sensor.hall_motion
      to: "on"
    condition:
      condition: and
      conditions:
        - condition: sun
          after: sunset
          before_offset: "-1:00:00"
        - condition: time
          before: '22:59:55'
    action:
      service: homeassistant.turn_on
      entity_id: script.hallbright
  - alias: halldim
    trigger:
      platform: state
      entity_id: binary_sensor.hall_motion
      to: "on"
    condition:
      condition: or
      conditions:
        - condition: time
          before: 08:00:00
        - condition: time
          after: '23:00:00'
    action:
      service: homeassistant.turn_on
      entity_id: script.halldim
  - alias: halloff
    trigger:
      platform: state
      entity_id: binary_sensor.hall_motion
      state: "off"
      for:
        minutes: 3
    action:
      service: homeassistant.turn_off
      entity_id: light.hall_light
