sensor:
  - platform: mqtt
    state_topic: "avondale/temp/set"
    name: Target temperature
    unit_of_measurement: "°C"
  - platform: mqtt
    state_topic: 'avondale/temp/both'
    name: 'Lounge temperature'
    unit_of_measurement: '°C'
    value_template: '{{ value_json.temperature }}'
  - platform: mqtt
    state_topic: 'avondale/temp/both'
    name: 'Lounge humidity'
    unit_of_measurement: '%'
    value_template: '{{ value_json.humidity }}'
  - platform: mold_indicator
    indoor_temp_sensor: sensor.lounge_temperature
    indoor_humidity_sensor: sensor.lounge_humidity
    outdoor_temp_sensor: sensor.owm_temperature
    calibration_factor: 2.0

switch:
  - platform: mqtt
    name: boiler
    state_topic: 'avondale/boiler/status'
    command_topic: 'avondale/boiler/switch'
    optimistic: false

light:
  - platform: mqtt
    name: heating
    command_topic: 'avondale/temp/poo/switch'
    state_topic: 'avondale/temp/poo/status'
    brightness_command_topic: 'avondale/temp/set'
    brightness_state_topic: 'avondale/temp/set'
    optimistic: false
    brightness_scale: 102

climate:
  - platform: generic_thermostat
    name: Home
    heater: switch.boiler
    target_sensor: sensor.lounge_temperature
    min_temp: 7
    max_temp: 32
    target_temp: 19

group:
  Heating:
    view: yes
    icon: mdi:radiator
    entities:
      - switch.boiler
      - climate.home
      - sensor.target_temperature
      - sensor.lounge_temperature
      - sensor.lounge_humidity
      - sensor.mold_indicator
      - group.auto_heating_settings
      - group.set_the_temperature
      - script.boost_the_heating
      - group.boost
  Thermostat quick settings:
    entities:
      - switch.boiler
      - input_slider.slider1
      - climate.home
  Boost:
    entities:
      - script.boost_the_heating
      - input_select.boostdelay
  Auto heating settings:
    entities:
      - input_select.tempfor6
      - input_select.preheatdelay
      - input_select.tempfornormal
      - input_select.away_from_home_temp
      - automation.set_heating_to_21_if_below_3_degrees_outside_in_morning
      - automation.heating_on_at_6
      - automation.turn_boiler_on_when_people_return
  Set the temperature:
    entities:
      - input_slider.slider1

input_slider:
  slider1:
    name: temperature
    initial: 22
    min: 10
    max: 30
    step: 1

input_select:
  tempfor6:
    name: Set temperature for 6am
    options:
      - 5
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
    initial: 19
  tempfornormal:
    name: Set the normal temperature
    options:
      - 5
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
    initial: 18
  preheatdelay:
    name: morning preheat length
    options:
      - 00:01
      - 00:30
      - 01:00
      - 01:30
      - 02:00
      - 02:30
    initial: 01:00
  boostdelay:
    name: Boost heating length
    options:
      - 00:01
      - 00:30
      - 01:00
      - 01:30
      - 02:00
      - 02:30
    initial: 01:00
  away_from_home_temp:
    name: temperature for when away from home
    options:
      - 5
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
    initial: 17

script:
  boilerwhenhome:
    sequence:
      - service_template: climate.set_temperature
        data_template:
          temperature: " {{ states.input_select.tempfornormal.state | float + 2 }} "
      - service: notify.pushbullet
        data:
          message: "This was done automatically as someone has returned home"
          title: "Boiler set to 2 degrees higher than normal"
      - service: notify.kodi
        data_template:
          message: "This was done automatically for 10 minutes as someone has returned home"
          title: "Boiler set to 21 it is currently {{ states.sensor.lounge_temperature.state }}"
      - delay:
          minutes: 10
      - service_template: climate.set_temperature
        data_template:
          temperature: " {{ states.input_select.tempfornormal.state | int }} "
      - service: notify.kodi
        data_template:
          message: "This was done automatically 10 minutes after someone returned"
          title: "Boiler set to the normal temperature"

  warmhouseat6:
    sequence:
      - service_template: climate.set_temperature
        data_template:
          temperature: " {{ states.input_select.tempfor6.state | int }} "
      - service_template: notify.kodi
        data_template:
          message: "This was done automatically"
          title: "I set the boiler to {{ states.input_select.tempfor6.state | int }}C"
      - delay: '{{ states.input_select.preheatdelay.state }}:00'
      - service_template: climate.set_temperature
        data_template:
          temperature: " {{ states.input_select.tempfornormal.state | int }} "
      - service_template: notify.kodi
        data_template:
          message: "This was done automatically"
          title: "I set the boiler to {{ states.input_select.tempfornormal.state | int }}C"
      - service_template: notify.pushbullet
        data_template:
          message: "This was done automatically"
          title: "I set the boiler to {{ states.input_select.tempfornormal.state | int }}C"

  boost_the_heating:
    sequence:
      - service_template: climate.set_temperature
        data_template:
          temperature: " {{ states.sensor.lounge_temperature.state | float + 3 }} "
      - service_template: notify.kodi
        data_template:
          message: "I set the boiler to 3 degrees higher for the specified time"
          title: "Heating boost!"
      - service_template: notify.pushbullet
        data_template:
          message: "I set the boiler to 3 degrees higher for the specified time"
          title: "Heating boost!"
      - delay: '{{ states.input_select.boostdelay.state }}:00'
      - service_template: climate.set_temperature
        data_template:
          temperature: " {{ states.input_select.tempfornormal.state | int }} "
      - service_template: notify.kodi
        data_template:
          message: "This was done automatically after the heating boost"
          title: "I set the boiler to {{ states.input_select.tempfornormal.state | int }}C "
      - service_template: notify.pushbullet
        data_template:
          message: "This was done automatically after the heating boost"
          title: "I set the boiler to {{ states.input_select.tempfornormal.state | int }}C "

##############################################################
##############################################################
#                Boiler
##############################################################
##############################################################
automation:
  - alias: Set MQTT temp from Slider
    trigger:
      platform: state
      entity_id: input_slider.slider1
    action:
      - service: mqtt.publish
        data_template:
          topic: "avondale/temp/set"
          payload: '{{ states.input_slider.slider1.state | int }}'

  - alias: Set Climate from MQTT
    trigger:
      platform: mqtt
      topic: avondale/temp/set
    action:
      - service_template: climate.set_temperature
        data_template:
          temperature: " {{trigger.payload}} "
      - service_template: notify.pushbullet
        data_template:
          message: "This was done by a user"
          title: "Set the boiler to {{trigger.payload}}C"
      - service_template: notify.kodi
        data_template:
          message: "This was done by a user"
          title: "The boiler has been set to {{trigger.payload}}C"

  - alias: heating on at 6
    hide_entity: False
    trigger:
      platform: time
      after: '06:00:00'
    condition:
     condition: state
     entity_id: group.all_devices
     state: home
    action:
      - service: homeassistant.turn_on
        entity_id: script.warmhouseat6


  - alias: Turn boiler on when people return
    hide_entity: False
    trigger:
      platform: state
      entity_id: group.all_devices
      to: home
    action:
      - service: homeassistant.turn_on
        entity_id: script.boilerwhenhome

  - alias: set heating to 21 if below 3 degrees outside in morning
    hide_entity: False
    trigger:
      platform: time
      after: '05:55:00'
    condition:
     condition: and
     conditions:
       - condition: state
         entity_id: group.all_devices
         state: home
       - condition: numeric_state
         entity_id: 'sensor.owm_temperature'
         below: '3'
    action:
      - service: input_select.select_option
        entity_id: input_select.tempfor6
        data:
          option: 21
