group:
  kitchenview:
    view: yes
    icon: mdi:kettle
    entities:
      - switch.coffee_machine
      - switch.cabinet_lights
  kitchen:
    icon: mdi:kettle
    entities:
      - switch.coffee_machine
      - switch.cabinet_lights

switch:
  - platform: mqtt
    name: coffee machine
    state_topic: 'coffee/1/status'
    command_topic: 'coffee/1/switch'
    optimistic: false
  - platform: mqtt
    name: capuccino
    state_topic: 'coffee/2/status'
    command_topic: 'coffee/2/switch'
    optimistic: false
  - platform: mqtt
    name: latte
    state_topic: 'coffee/3/status'
    command_topic: 'coffee/3/switch'
    optimistic: false
  - platform: mqtt
    name: espresso
    state_topic: 'coffee/4/status'
    command_topic: 'coffee/4/switch'
    optimistic: false
  - platform: mqtt
    name: lungo
    state_topic: 'coffee/5/status'
    command_topic: 'coffee/5/switch'
    optimistic: false
  - platform: mqtt
    name: "cabinet lights"
    state_topic: "avondale/sonoff/touch/1/stat"
    command_topic: "avondale/sonoff/touch/1"
    qos: 0
    payload_on: "1on"
    payload_off: "1off"
    retain: false

automation:
  - alias: coffeeoff
    trigger:
      platform: state
      entity_id: switch.coffee_machine
      to: "on"
      for:
        minutes: 10
    action:
      service: homeassistant.turn_off
      entity_id: switch.coffee_machine
