octoprint:
  host: "10.10.10.195"
  api_key: !secret octoapi
  bed: true
  number_of_tools: 1
switch:
  platform: mqtt
  name: "Printer"
  state_topic: "home/sonoff/printer/1/stat"
  command_topic: "home/sonoff/printer/1"
  qos: 1
  payload_on: "on"
  payload_off: "off"
  retain: true
sensor:
  - platform: octoprint
    name: OctoPrint
    monitored_conditions:
      - Current State
      - Temperatures
      - Job Percentage
#  - platform: command_line
#    command: python3 /home/homeassistant/.homeassistant/conf/octo-control/octo-control.py --apikey 'absalomoctoprintapi' --host 10.10.10.195 --port 80 --left-time
#    name: time left on print
#    scan_interval: 5
  - platform: mqtt
    name: extrudermm
    state_topic: "octoprint/extruder/mm"
  - platform: mqtt
    name: extrudertemp
    state_topic: "octoprint/extruder/temp"
  - platform: mqtt
    name: heatbedtemp
    state_topic: "octoprint/bed/temp"
# Sonoff Pow -------------------------------------

  - platform: mqtt
    name: "Printer Power"
    state_topic: "home/sonoff/printer/1/power"
    qos: 1
    unit_of_measurement: "W"
    value_template: "{{ value_json.Power }}"

  - platform: mqtt
    name: "Printer Voltage"
    state_topic: "home/sonoff/printer/1/power"
    qos: 1
    unit_of_measurement: "V"
    value_template: "{{ value_json.Voltage }}"

binary_sensor:
  - platform: octoprint
    monitored_conditions:
      - Printing
      - Printing Error
    name: Octoprint

camera:
  platform: mjpeg
  mjpeg_url: !secret printercam
  name: printcam

input_number:
  bedtemp:
    name: temperature of the bed
    initial: 5
    min: 0
    max: 100
    step: 5
  exttemp:
    name: temperature of the extruder
    initial: 5
    min: 0
    max: 255
    step: 5
  extrude:
    name: extrude amount
    initial: 5
    min: 0
    max: 200
    step: 5


#  https://github.com/dragondgold/octo-control  for below shell commands
shell_command:
  bedtemp95: python3 /home/homeassistant/.homeassistant/conf/octo-control/octo-control.py --apikey absalomoctoprintapi --host 10.10.10.195 --port 80 --set-bed-temp 95
  bedtemp0: python3 /home/homeassistant/.homeassistant/conf/octo-control/octo-control.py --apikey absalomoctoprintapi --host 10.10.10.195 --port 80 --set-bed-temp 5
  exttemp240: python3 /home/homeassistant/.homeassistant/conf/octo-control/octo-control.py --apikey absalomoctoprintapi --host 10.10.10.195 --port 80 --send-gcode 'M104 S240'
  exttemp0: python3 /home/homeassistant/.homeassistant/conf/octo-control/octo-control.py --apikey absalomoctoprintapi --host 10.10.10.195 --port 80 --send-gcode 'M104 S0'
  pause: python3 /home/homeassistant/.homeassistant/conf/octo-control/octo-control.py --apikey absalomoctoprintapi --host 10.10.10.195 --port 80 --pause
  resume: python3 /home/homeassistant/.homeassistant/conf/octo-control/octo-control.py --apikey absalomoctoprintapi --host 10.10.10.195 --port 80 --resume
  cancel: python3 /home/homeassistant/.homeassistant/conf/octo-control/octo-control.py --apikey absalomoctoprintapi --host 10.10.10.195 --port 80 --cancel
  bedtempslider: "python3 /home/homeassistant/.homeassistant/conf/octo-control/octo-control.py --apikey absalomoctoprintapi --host 10.10.10.195 --port 80 --send-gcode 'M140 S{{ states.input_number.bedtemp.state }}'"
  exttempslider: "python3 /home/homeassistant/.homeassistant/conf/octo-control/octo-control.py --apikey absalomoctoprintapi --host 10.10.10.195 --port 80 --send-gcode 'M104 S{{ states.input_number.exttemp.state }}'"
  homexy: python3 /home/homeassistant/.homeassistant/conf/octo-control/octo-control.py --apikey absalomoctoprintapi --host 10.10.10.195 --port 80 --send-gcode 'G28 X0 Y0'
  homez: python3 /home/homeassistant/.homeassistant/conf/octo-control/octo-control.py --apikey absalomoctoprintapi --host 10.10.10.195 --port 80 --send-gcode 'G28 Z0'
  homexyz: python3 /home/homeassistant/.homeassistant/conf/octo-control/octo-control.py --apikey absalomoctoprintapi --host 10.10.10.195 --port 80 --send-gcode 'G28 X0 Y0 Z0'
  filamentclean: python3 /home/homeassistant/.homeassistant/conf/octo-control/octo-control.py --apikey absalomoctoprintapi --host 10.10.10.195 --port 80 --send-gcode 'G28 X0 Y0' 'G0 Z50' 'M104 S240'
  extrudemanual: "python3 /home/homeassistant/.homeassistant/conf/octo-control/octo-control.py --apikey absalomoctoprintapi --host 10.10.10.195 --port 80 --send-gcode 'G1 E{{ states.sensor.extrudermm.state }} F300'"
  extrude: "python3 /home/homeassistant/.homeassistant/conf/octo-control/octo-control.py --apikey absalomoctoprintapi --host 10.10.10.195 --port 80 --send-gcode 'G1 E{{ states.input_number.extrude.state }} F300'"
  exttempmanual: "python3 /home/homeassistant/.homeassistant/conf/octo-control/octo-control.py --apikey absalomoctoprintapi --host 10.10.10.195 --port 80 --send-gcode 'M104 S{{ states.sensor.extrudertemp.state }}'"
  bedtempmanual: "python3 /home/homeassistant/.homeassistant/conf/octo-control/octo-control.py --apikey absalomoctoprintapi --host 10.10.10.195 --port 80 --send-gcode 'M140 S{{ states.sensor.heatbedtemp.state }}'"

script:
  bedtemp95:
    sequence:
    - service: shell_command.bedtemp95
  bedtemp0:
    sequence:
    - service: shell_command.bedtemp0
  exttemp0:
    sequence:
    - service: shell_command.exttemp0
  exttemp240:
    sequence:
    - service: shell_command.exttemp240
  exttempslider:
    sequence:
    - service: shell_command.exttempslider
  bedtempslider:
    sequence:
    - service: shell_command.bedtempslider
  heatoff:
    sequence:
    - service: shell_command.bedtemp0
    - service: shell_command.exttemp0
  heatall:
    sequence:
    - service: shell_command.bedtemp95
    - service: shell_command.exttemp240
  pause:
    sequence:
    - service: shell_command.pause
  resume:
    sequence:
    - service: shell_command.resume
  cancel:
    sequence:
    - service: shell_command.cancel
  homexy:
    sequence:
    - service: shell_command.homexy
  homexyz:
    sequence:
    - service: shell_command.homexyz
  homez:
    sequence:
    - service: shell_command.homez
  filamentclean:
    sequence:
    - service: shell_command.filamentclean
  extrudemanual:
    sequence:
    - service: shell_command.extrudemanual
  bedtempmanual:
    sequence:
    - service: shell_command.bedtempmanual
  exttempmanual:
    sequence:
    - service: shell_command.exttempmanual
  extrude:
    sequence:
    - service: shell_command.extrude

group:
  3D Printer:
    view: yes
    icon: mdi:printer-3d
    entities:
      - group.printer
      - group.control_temperatures
      - group.control
      - camera.printcam
      - sensor.printer_voltage
      - sensor.printer_power
      - switch.printer

  Control temperatures:
    entities:
      - input_number.exttemp
      - input_number.bedtemp
      - script.bedtemp0
      - script.bedtemp95
      - script.exttemp0
      - script.exttemp240
      - script.exttempslider
      - script.bedtempslider
      - script.heatall
      - script.heatoff

  Control:
    entities:
      - input_number.extrude
      - script.resume
      - script.pause
      - script.cancel
      - script.homexy
      - script.homexyz
      - script.homez
      - script.filamentclean
      - script.extrude

  Printer:
    entities:
      - sensor.octoprint_actual_bed_temp
      - sensor.octoprint_actual_tool0_temp
      - sensor.octoprint_current_state
      - sensor.octoprint_job_percentage
      - sensor.octoprint_target_bed_temp
      - sensor.octoprint_target_tool0_temp
      - binary_sensor.octoprint_printing
      - binary_sensor.octoprint_printing_error
      - automation.notify_about_printer_error

automation:
  - alias: notify about printer error
    trigger:
      platform: state
      entity_id: binary_sensor.octoprint_printing_error
      to: 'on'
    action:
      - service_template: notify.pushbullet
        data_template:
          message: "Something has triggered an octoprint printer error"
          title: "Printer error"
      - service_template: notify.kodi
        data_template:
          message: "Something has triggered an octoprint printer error"
          title: "Printer error"
