octoprint:
  host: "10.10.10.195"
  api_key: !secret octoapi

sensor:
  - platform: octoprint
    name: OctoPrint
    monitored_conditions:
      - Current State
      - Temperatures
      - Job Percentage

binary_sensor:
  - platform: octoprint
    monitored_conditions:
      - Printing
      - Printing Error
    name: Octoprint

camera:
  platform: mjpeg
  mjpeg_url: !secret printercam
  name: printcam

input_slider:
  bedtemp:
    name: temperature of the bed
    initial: 5
    min: 0
    max: 100
    step: 5
  exttemp:
    name: temperature of the extruder
    initial: 5
    min: 0
    max: 255
    step: 1


#  https://github.com/dragondgold/octo-control  for below shell commands
shell_command:
  bedtemp95: 'python3 /home/hass/.homeassistant/conf/octo-control/octo-control.py --apikey !secret octoapi --host 10.10.10.195 --port 80 --set-bed-temp 95'
  bedtemp0: 'python3 /home/hass/.homeassistant/conf/octo-control/octo-control.py --apikey !secret octoapi --host 10.10.10.195 --port 80 --set-bed-temp 0'
  exttemp240: 'python3 /home/hass/.homeassistant/conf/octo-control/octo-control.py --apikey !secret octoapi --host 10.10.10.195 --port 80 --ext-target 240'
  exttemp0: 'python3 /home/hass/.homeassistant/conf/octo-control/octo-control.py --apikey !secret octoapi --host 10.10.10.195 --port 80 --ext-target 0'
  pause: 'python3 /home/hass/.homeassistant/conf/octo-control/octo-control.py --apikey !secret octoapi --host 10.10.10.195 --port 80 --pause'
  resume: 'python3 /home/hass/.homeassistant/conf/octo-control/octo-control.py --apikey !secret octoapi --host 10.10.10.195 --port 80 --resume'
  print: 'python3 /home/hass/.homeassistant/conf/octo-control/octo-control.py --apikey !secret octoapi --host 10.10.10.195 --port 80 --print'
  bedtempslider: 'python3 /home/hass/.homeassistant/conf/octo-control/octo-control.py --apikey !secret octoapi --host 10.10.10.195 --port 80 --set-bed-temp {{ states.input_slider.bedtemp.state }}'
  exttempslider: 'python3 /home/hass/.homeassistant/conf/octo-control/octo-control.py --apikey !secret octoapi --host 10.10.10.195 --port 80 --ext-target {{ states.input_slider.exttemp.state }}'

  timeleft: python3 /home/hass/.homeassistant/conf/octo-control/octo-control.py --apikey '!secret octoapi' --host 10.10.10.195 --port 80 --left-time


script:
  bedtemp95:
    sequence:
    - service: shell_command.bedtemp95
  bedtemp0:
    sequence:
    - service: shell_command.bedtemp0
  exttemp0:
    sequence:
    - service: shell_command.exttemp0
  exttemp240:
    sequence:
    - service: shell_command.exttemp240
  exttempslider:
    sequence:
    - service: shell_command.exttempslider
  bedtempslider:
    sequence:
    - service: shell_command.bedtempslider
  heatoff:
    sequence:
    - service: shell_command.bedtemp0
    - service: shell_command.exttemp0
  heatall:
    sequence:
    - service: shell_command.bedtemp95
    - service: shell_command.exttemp240
  pause:
    sequence:
    - service: shell_command.pause
  resume:
    sequence:
    - service: shell_command.resume
  print:
    sequence:
    - service: shell_command.print
group:
  3D Printer:
    view: yes
    icon: mdi:printer-3d
    entities:
      - group.printer
      - group.control
      - camera.printcam
  Control:
    entities:
      - input_slider.exttempslider
      - input_slider.bedtempslider
      - script.bedtemp0
      - script.bedtemp95
      - script.exttemp0
      - script.exttemp240
      - script.exttempslider
      - script.bedtempslider
      - script.heatall
      - script.heatoff
      - script.resume
      - script.pause
      - script.print

  Printer:
    entities:
      - sensor.octoprint_actual_bed_temp
      - sensor.octoprint_actual_tool0_temp
      - sensor.octoprint_current_state
      - sensor.octoprint_job_percentage
      - sensor.octoprint_target_bed_temp
      - sensor.octoprint_target_tool0_temp
      - binary_sensor.octoprint_printing
      - binary_sensor.octoprint_printing_error
      - automation.notify_about_printer_error

automation:
  - alias: notify about printer error
    trigger:
      platform: state
      entity_id: binary_sensor.octoprint_printing_error
      to: 'on'
    action:
      - service_template: notify.pushbullet
        data_template:
          message: "Something has triggered an octoprint printer error"
          title: "Printer error"
      - service_template: notify.kodi
        data_template:
          message: "Something has triggered an octoprint printer error"
          title: "Printer error"
