shell_command:
  rebootpi: "sudo reboot"

script:
  reboot_pi:
    alias: Reboot the Pi
    sequence:
      - service: shell_command.rebootpi

switch:
  - platform: wake_on_lan
    name: router
    mac_address: "dc:9f:db:29:a0:bc"
    host: 10.10.10.1

automation:
  - alias: all on
    trigger:
      platform: state
      entity_id: switch.router
      to: off
    action:
      - service: homeassistant.turn_on
        entity_id: script.reboot_pi
      - service_template: notify.pushbullet
        data_template:
          message: "This was done because HA lost connection to the router"
          title: "REBOOT"
      - service_template: notify.kodi
        data_template:
          message: "This was done because HA lost connection to the router"
          title: "REBOOT"
