sensor:
  - platform: haveibeenpwned
    email:
      - !secret yahoo
      - !secret hotmail
      - !secret me
      - !secret icloud
      - !secret gmail
  - platform: transmission
    host: !secret transmissionhost
    username: !secret transmissionuser
    password: !secret transmissionpass
    monitored_variables:
      - 'current_status'
      - 'download_speed'
      - 'upload_speed'
  - platform: speedtest
    minute:
      - 0
      - 20
      - 40
      - 50
    monitored_conditions:
      - download
      - upload
  - platform: dnsip
  - platform: dnsip
    hostname: !secret parentsdns
    resolver: 8.8.8.8
    name: Parents DNS
  - platform: dnsip
    hostname: !secret cornwalldns
    resolver: 8.8.8.8
    name: Cornwall DNS
  - platform: command_line
    name: SSL cert expiry
    unit_of_measurement: days
    scan_interval: 10800
    command: !secret sslcert

# digital_ocean:
#   access_token: !secret digocean
# switch:
#   - platform: digital_ocean
#     droplets:
#       - 'ubuntu-512mb-sgp1-01'
# binary_sensor:
#   - platform: digital_ocean
#     droplets:
#       - 'ubuntu-512mb-sgp1-01'

shell_command:
  renew_ssl: ~/certbot/certbot-auto renew --quiet --no-self-upgrade --standalone --preferred-challenges http-01

automation:
  - alias: 'Auto Renew SSL Cert'
    trigger:
      platform: numeric_state
      entity_id: sensor.ssl_cert_expiry
      below: 29
    action:
      service: shell_command.renew_ssl

group:
  Network:
    entities:
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.transmission_down_speed
      - sensor.transmission_status
      - sensor.transmission_up_speed
  Breach:
    entities:
      - sensor.breaches_samabsalomyahoocom
      - sensor.breaches_samabsalommecom
      - sensor.breaches_sam_absalomhotmailcom
      - sensor.breaches_samabsalomicloudcom
      - sensor.breaches_sabsalom93gmailcom
  DNS:
    entities:
      - sensor.myipopendnscom
      - sensor.huntsfieldddnsnet
      - sensor.penymorfaddnsnet
  tinterweb:
    name: Misc
    icon: mdi:ethernet
    view: yes
    entities:
      - group.breach
      - group.network
      - group.dns

      # - binary_sensor.ubuntu512mbsgp101
      # - switch.ubuntu512mbsgp101
