group:
  Weather:
    view: yes
    icon: mdi:weather-cloudy
    entities:
      - group.weather1
      - group.weather2
      - group.flying

  Weather1:
    entities:
      - sun.sun
      - sensor.owm_cloud_coverage
      - sensor.owm_condition
      - sensor.owm_humidity
      - sensor.owm_pressure
      - sensor.owm_rain
      - sensor.owm_temperature
      - sensor.owm_wind_speed
      - sensor.owm_snow
  Weather2:
    entities:
      - sensor.pws_alerts
      - sensor.pws_dewpoint_c
      - sensor.pws_feelslike_c
      - sensor.pws_elevation
      - sensor.pws_precip_1hr_metric
      - sensor.pws_precip_today_metric
      - sensor.pws_pressure_mb
      - sensor.pws_pressure_trend
      - sensor.pws_relative_humidity
      - sensor.pws_solarradiation
      - sensor.pws_temp_c
      - sensor.pws_UV
      - sensor.pws_weather
      - sensor.pws_wind_degrees
      - sensor.pws_wind_dir
      - sensor.pws_wind_gust_mph
      - sensor.pws_wind_mph
  Flying:
    entities:
      - sensor.pws_dewpoint_c
      - sensor.pws_feelslike_c
      - sensor.pws_pressure_mb
      - sensor.pws_temp_c
      - sensor.pws_visibility_km
      - sensor.pws_visibility_mi
      - sensor.pws_wind_degrees
      - sensor.pws_wind_dir
      - sensor.pws_wind_gust_kph
      - sensor.pws_wind_kph

sensor:
  - platform: darksky
    api_key: !secret darkskyapi
    monitored_conditions:
      - summary
      - precip_type
      - precip_intensity
      - precip_probability
      - temperature
      - apparent_temperature
      - dew_point
      - wind_speed
      - wind_bearing
      - cloud_cover
      - humidity
      - pressure
      - visibility
      - ozone
      - minutely_summary
      - hourly_summary
      - daily_summary
      - icon
      - nearest_storm_distance
  - platform: openweathermap
    api_key: !secret openweatherkey
    monitored_conditions:
      - weather
      - temperature
      - wind_speed
      - humidity
      - pressure
      - clouds
      - rain
      - snow
  - platform: wunderground
    api_key: !secret wundergroundapi
    monitored_conditions:
      - alerts
      - dewpoint_c
      - dewpoint_f
      - dewpoint_string
      - feelslike_c
      - feelslike_f
      - feelslike_string
      - heat_index_c
      - heat_index_f
      - heat_index_string
      - elevation
      - location
      - observation_time
      - precip_1hr_in
      - precip_1hr_metric
      - precip_1hr_string
      - precip_today_in
      - precip_today_metric
      - precip_today_string
      - pressure_in
      - pressure_mb
      - pressure_trend
      - relative_humidity
      - station_id
      - solarradiation
      - temperature_string
      - temp_c
      - temp_f
      - UV
      - visibility_km
      - visibility_mi
      - weather
      - wind_degrees
      - wind_dir
      - wind_gust_kph
      - wind_gust_mph
      - wind_kph
      - wind_mph
      - wind_string
